# Generated by Django 4.1.3 on 2026-06-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
