# Generated by Django 5.2.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_newsarticle_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineArticleEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.CharField(db_index=True, max_length=500, unique=True)),
                ("url", models.URLField(max_length=500)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("pub_date", models.DateTimeField(db_index=True)),
                ("embedding_model", models.CharField(max_length=100)),
                ("embedding", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Baseline Article Embedding",
                "verbose_name_plural": "Baseline Article Embeddings",
                "ordering": ["-pub_date"],
                "indexes": [
                    models.Index(
                        fields=["pub_date", "embedding_model"],
                        name="core_baseli_pub_dat_7d2a1c_idx",
                    ),
                ],
            },
        ),
    ]
