# Generated by Django 4.1.3 on 2026-07-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_baselinearticleembedding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='baselinearticleembedding',
            new_name='core_baseli_pub_dat_4ba1e2_idx',
            old_name='core_baseli_pub_dat_7d2a1c_idx',
        ),
    ]
